name: Run Python

on:
  push:
    branches: [main]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run program
        run: python hello.py